apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: nginx
    namespace: argocd
spec:
    destination:
        namespace: default
        server: https://kubernetes.default.svc
    project: default
    source:
        path: deploy/components/nginx
        repoURL: https://github.com/p1kalinga/holos.git
        targetRevision: main
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
            - ServerSideApply=true
